version: 2

jobs:

  build:
    docker:
      - image: circleci/node:9

    working_directory: ~/repo

    steps:
      - checkout
      - run: yarn add tmp
      - run: .circleci/node_modules/.bin/text-run --offline
